select GL.NAME,GJH.JE_CATEGORY,GJH.JE_SOURCE,GJH.PERIOD_NAME,GCC.SEGMENT4 ACCOUNT,GCC.SEGMENT3 COST_CENTER,SUM(NVL(GJL.ACCOUNTED_DR,0)) DR, SUM(NVL(GJL.ACCOUNTED_CR,0)) CR,SUM(NVL(GJL.ACCOUNTED_DR,0))-SUM(NVL(GJL.ACCOUNTED_CR,0)) BAL
 FROM GL_JE_HEADERS GJH, 
      GL_JE_LINES GJL,
      GL_CODE_COMBINATIONS_KFV GCC,
      GL_LEDGERS GL, 
      FND_LOOKUP_VALUES_VL C
      WHERE     GJH.CURRENCY_CODE = 'BDT'
      AND GJH.ACTUAL_FLAG = 'A'
      AND GJH.STATUS = 'P'
      AND GJL.STATUS = 'P'
      AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
      AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
      AND GCC.SEGMENT4||GCC.SEGMENT3 = C.LOOKUP_CODE
      AND GL.ledger_id=GJH.ledger_id 
    AND GL.ledger_id = 2021                                      --2022
    AND GCC.SEGMENT2 = '199'
    AND LOOKUP_TYPE = 'XX_GL_ALLOCATION_MAPING'
    and GJH.PERIOD_NAME = 'JAN-24'
    GROUP BY GL.NAME,GJH.JE_CATEGORY,GJH.JE_SOURCE,GJH.PERIOD_NAME,GCC.SEGMENT4,GCC.SEGMENT3
    HAVING SUM(NVL(GJL.ACCOUNTED_DR,0))-SUM(NVL(GJL.ACCOUNTED_CR,0)) <>0
    --ORDER BY GCC.SEGMENT4;