-------------------
---Pending For PCL
---ERP Period-Wise Resource Cost
-- Have to make a form
-------------------

CREATE OR REPLACE VIEW XX_PRIOD_RSC_COST
AS
SELECT ORGANIZATION_ID, RESOURCES, RESOURCE_DESC, PERIOD_NAME, RESOURCE_USAGE, TRANS_QTY_UM, PERIOD_NET_BALANCE, ROUND(RESOURCE_RATE,9) RESOURCE_RATE, 
ROUND(NVL((RESOURCE_RATE * RESOURCE_USAGE),0),9) APPLIED_NET_BALANCE FROM(
WITH DTL AS(
SELECT ORGANIZATION_ID, RESOURCES, RESOURCE_DESC, PERIOD_NAME,
RESOURCE_USAGE, TRANS_QTY_UM, NVL(SUM(NVL(PERIOD_NET_BALANCE,0)),0) PERIOD_NET_BALANCE--, NVL(SUM(NVL(PERIOD_NET_BALANCE,0)) / NVL(RESOURCE_USAGE,0),0) RESOURCE_RATE
FROM(
SELECT ORGANIZATION_ID, PERIOD_NAME, RESOURCES, RESOURCE_DESC,
SUM(RESOURCE_USAGE) RESOURCE_USAGE, TRANS_QTY_UM, PERIOD_NET_BALANCE--, (PERIOD_NET_BALANCE/SUM(RESOURCE_USAGE)) RESOURCE_RATE
FROM (
SELECT A.*, BAL.PERIOD_NAME, (BAL.PERIOD_NET_DR - BAL.PERIOD_NET_CR)PERIOD_NET_BALANCE FROM
(
SELECT H.ORGANIZATION_ID, H.BATCH_NO,H.BATCH_ID, CC.CODE_COMBINATION_ID,
CC.SEGMENT3 Natural_ac,CC.SEGMENT2 Location, CC.SEGMENT5 cost_center, LV.LOOKUP_CODE,
CRM.RESOURCES, CRM.RESOURCE_DESC,
BSR.RESOURCE_USAGE, 
BSR.TRANS_QTY_UM
FROM GME_BATCH_HEADER H,
GME_MATERIAL_DETAILS D,
MTL_SYSTEM_ITEMS_B_KFV MSI,
GME_BATCH_STEPS STEP,
GMD_OPERATIONS_VL OPER,
GME_BATCH_STEP_ACTIVITIES BSA,
GMD_ACTIVITIES_VL ACT,
GME_RESOURCE_TXNS BSR,
CR_RSRC_MST_VL CRM,
-------For GL-------------------
GL_CODE_COMBINATIONS_KFV    CC,
----GL_BALANCES    BAL,
FND_LOOKUP_VALUES_VL        LV,
FND_FLEX_VALUES_VL          FLEX,
FND_ID_FLEX_SEGMENTS_VL     FVD,
FND_SEGMENT_ATTRIBUTE_VALUES SAV
--------------------------------
WHERE H.BATCH_ID = D.BATCH_ID
AND   D.LINE_TYPE = 1  --1 Mean Product
AND D.ORGANIZATION_ID = MSI.ORGANIZATION_ID
AND D.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
AND H.BATCH_ID = STEP.BATCH_ID
AND STEP.OPRN_ID = OPER.OPRN_ID
AND STEP.BATCH_ID = BSA.BATCH_ID 
AND STEP.BATCHSTEP_ID = BSA.BATCHSTEP_ID
AND ACT.ACTIVITY = BSA.ACTIVITY
AND BSA.BATCH_ID=  BSR.DOC_ID
AND BSR.RESOURCES = CRM.RESOURCES
AND LV.TAG = CRM.RESOURCES
AND BATCH_STATUS IN (3,4)
-----AND TRUNC(H.ACTUAL_CMPLT_DATE) BETWEEN TRUNC(TO_DATE(:P_PERIOD,'MON-YY'),'MM') AND LAST_DAY(TO_DATE(:P_PERIOD,'MON-YY'))
-------For GL----------------
AND CC.TEMPLATE_ID IS NULL
AND CC.SUMMARY_FLAG = 'N'
AND FVD.ID_FLEX_NUM = SAV.ID_FLEX_NUM
AND FVD.ID_FLEX_CODE = SAV.ID_FLEX_CODE
AND FVD.APPLICATION_ID = SAV.APPLICATION_ID
AND FVD.APPLICATION_COLUMN_NAME = SAV.APPLICATION_COLUMN_NAME
AND FVD.FLEX_VALUE_SET_ID = FLEX.FLEX_VALUE_SET_ID
AND FVD.ID_FLEX_NUM = CC.CHART_OF_ACCOUNTS_ID
AND FLEX.FLEX_VALUE =
 DECODE (SUBSTR (FVD.APPLICATION_COLUMN_NAME, 8, 1),
         '1', CC.SEGMENT1,
         '2', CC.SEGMENT2,
         '3', CC.SEGMENT3,
         '4', CC.SEGMENT4,
         '5', CC.SEGMENT5,
         '6', CC.SEGMENT6,
         '7', CC.SEGMENT7,
         '8', CC.SEGMENT8,
         '9', CC.SEGMENT9,
         '10', CC.SEGMENT10,
         '11', CC.SEGMENT11)
AND FVD.APPLICATION_ID = 101
AND FVD.ID_FLEX_CODE = 'GL#'
AND SAV.SEGMENT_ATTRIBUTE_TYPE = 'GL_ACCOUNT'
AND SAV.ATTRIBUTE_VALUE = 'Y'
AND CC.SEGMENT4 || CC.SEGMENT3 = LV.LOOKUP_CODE ----NATURAL A/C + cost center
AND LV.LOOKUP_TYPE = 'XX_MFG_RESOURCE_COST_CALC'
AND CC.SEGMENT3 = SUBSTR(LV.LOOKUP_CODE,8,4)----cost center
AND CC.SEGMENT2 = 199 --Location
----AND BAL.PERIOD_NAME = TO_CHAR(:P_PERIOD,'MON-YYYY')
--and CRM.RESOURCES = 'MAN_OMERA_PO4'
--AND H.BATCH_NO=100
ORDER BY CRM.RESOURCES
) A
LEFT JOIN GL_BALANCES    BAL 
ON A.CODE_COMBINATION_ID = BAL.CODE_COMBINATION_ID
AND BAL.CURRENCY_CODE = 'BDT'
AND BAL.ACTUAL_FLAG = 'A'
AND BAL.LEDGER_ID = 2021 --2021 OPL PRIMARY LEDGER  --2023 OCL PRIMARY LEDGER
-----AND BAL.PERIOD_NAME = :P_PERIOD
)
GROUP BY ORGANIZATION_ID, PERIOD_NAME, LOOKUP_CODE, RESOURCES, RESOURCE_DESC,TRANS_QTY_UM, PERIOD_NET_BALANCE--, RESOURCE_RATE
)
GROUP BY ORGANIZATION_ID, PERIOD_NAME, RESOURCES, RESOURCE_DESC,RESOURCE_USAGE, TRANS_QTY_UM
ORDER BY RESOURCES
)
(SELECT DTL.*, (NVL(DTL.PERIOD_NET_BALANCE,0) / DTL.RESOURCE_USAGE) RESOURCE_RATE
/*(CASE 
    WHEN RESOURCES IN ('FILLING-MC_PO1', 'LPG_PUMP_PO1') THEN 
     (SELECT SUM(DTL.RESOURCE_USAGE) FROM DTL WHERE RESOURCES IN ('FILLING-MC_PO1', 'LPG_PUMP_PO1')) 
    WHEN RESOURCES IN ('FILLING-MC_PO2', 'LPG_PUMP_PO2') THEN 
     (SELECT SUM(DTL.RESOURCE_USAGE) FROM DTL WHERE RESOURCES IN ('FILLING-MC_PO2', 'LPG_PUMP_PO2'))
    WHEN RESOURCES IN ('FILLING-MC_PO3', 'LPG_PUMP_PO3') THEN 
     (SELECT SUM(DTL.RESOURCE_USAGE) FROM DTL WHERE RESOURCES IN ('FILLING-MC_PO3', 'LPG_PUMP_PO3')) 
    WHEN RESOURCES IN ('FILLING-MC_PO4', 'LPG_PUMP_PO4') THEN 
     (SELECT SUM(DTL.RESOURCE_USAGE) FROM DTL WHERE RESOURCES IN ('FILLING-MC_PO4', 'LPG_PUMP_PO4')) 
ELSE
    DTL.RESOURCE_USAGE
END) RESOURCE_RATE */
FROM DTL))
WHERE PERIOD_NAME IS NOT NULL




SELECT *FROM XX_PRIOD_RSC_COST
WHERE PERIOD_NAME = :P_PERIOD_NAME;